### ISSUE TITLE
typo in 03_Digital_Ocean_Snapshots.md

### ISSUE THREAD

**Issue by extra808** [susanBuck/dwa15-fall2015-notes#11]
```
- Droplet settings -> Snapshots -> estore from Snapshot
+ Droplet settings -> Snapshots -> Restore from Snapshot
```

You might also mention that Digital Ocean will automatically start your droplet again after the snapshot is saved. At least it did for me but I used `sudo shutdown -h now`, not the web "Power Off" button.

**Comment by susanBuck** [comment]
Typo fixed, thanks!
