### ISSUE TITLE
foobar typo in Piggy Bank code

### ISSUE THREAD

**Issue by usojoe** [susanBuck/dwa15-fall2015-notes#12]
You left the following code on the Lecture 3 example. It calls an error to the page. Thought it might catch some students off guard if they were following along in class even though you did try and call this exact same error intentionally in the lecture, so most folks should catch it. Thought you should know this was left there in the example just in case it's not supposed to be there. Pretty sure it was intentional cuz you were trying to make sure we knew how to set error reporting...so... nevermind.  :))

    echo $foobar;

**Comment by susanBuck** [comment]
Ah, I did *not* want $foobar in the example example. It was copied over from when I was fiddling with the bank.php code and demonstrating the error.

So, removed it.

Thanks for pointing it out!

**Comment by usojoe** [comment]
Oh good! I went back and edited my response like 6 times as I watched the
lecture. At the end I still wasn't sure if you wanted it there or not.
Having it there was actually kind of helpful because it did make me learn
about error responses. Unfortunately if didn't have them turned on already,
I might not have seen it.
