### ISSUE TITLE
PATH_Variable.md remove end slash

### ISSUE THREAD

**Issue by extra808** [susanBuck/dwa15-fall2015-notes#13]
When exporting the updated path to make MAMP's version of PHP found first, I think paths aren't meant to be ended with a slash, i.e. this:
`export PATH="/Applications/MAMP/bin/php/php5.6.10/bin":$PATH`
rather than this:
`export PATH="/Applications/MAMP/bin/php/php5.6.10/bin/":$PATH`

Otherwise you get two slashes say when you run `which php`:
`/Applications/MAMP/bin/php/php5.6.10/bin//php`

It's mostly cosmetic as php still runs but could maybe create an issue say if a script was to compare the path as a string to an a stored string.

**Comment by susanBuck** [comment]
Fixed, thanks! Think my brain was still in Windows mode that does need the trailing slash.

ref: https://github.com/susanBuck/dwa15-fall2015-notes/commit/c6d230a672d64fc24b7a140f77c19d51eaae329a
