### ISSUE TITLE
05_Deploy_to_DigitalOcean.md adding sudo

### ISSUE THREAD

**Issue by extra808** [susanBuck/dwa15-fall2015-notes#14]
Unless already running as root, these commands probably require sudo:
`mv composer.phar composer`
`a2enmod rewrite`
`service apache2 restart` (after creating foobooks virtual host)

**Comment by susanBuck** [comment]
Good call. 

https://github.com/susanBuck/dwa15-fall2015-notes/commit/49441ed7630541cd971924369248857987823684
