### ISSUE TITLE
05_Deploy_to_DigitalOcean.md Permissions tweak

### ISSUE THREAD

**Issue by extra808** [susanBuck/dwa15-fall2015-notes#15]
Before changing ownership, the permissions set on storage/ and bootstrap/cache/ should already be 755, as is the rest. Therefore after changing the owner, there is no need to chmod the permissions to 755 again.

Assuming the user has ownership of the parent directory, /var/www/html, when they run `git clone` the repo directory's user and group will both be the user's and the permissions will be 775, group members have write access too. So, perhaps instead of `sudo chown -R www-data:www-data storage` where both the owner and group is changed, it's better to just use `sudo chown -R www-data storage`, leaving the group setting to that of the user. That way, with the 775 permissions, not just Apache but also the user has read/write access to everything.

BTW, I hadn't picked up on the fact that .gitignore files don't only have to be in the root of a repo but there can be others in any repo directory, sort of like .htaccess. I discovered this when I went looking to see if files you wouldn't want in your repo are excluded, files like the ones made in storage/framework/sessions/. That directory's .gitignore says to ignore everything but itself. The same is repeated in, I assume, all the web-writeable directories.

One advantage to everyone in class using Digital Ocean is there's no need to hunt down who the Apache user is. But if it was necessary for someone, a command line method is to run `ps -ef |grep apache2`. There will be one process instance that's owned by root but the rest will be the user. But since some environments may modify the user specifically for mod_php or use suEXEC, it's probably better to use a .php page. You can make a page containing <?php echo `whoami`; ?> to find out.

**Comment by susanBuck** [comment]
Agreed on just changing the ownership, and setting 775 as being unnecessary.
https://github.com/susanBuck/dwa15-fall2015-notes/commit/9e3c060a36ea4690ef13dad003573618cc46077f

I debated including the instructions on how to figure out who the Apache user is. Always a fine line between keeping the notes to the point for the given context vs. being comprehensive enough to work with all contexts. More advanced students can handle the latter, but it can over complicate things less advanced students. I think I'll do what I've done in other notes and include it in an extra Tips section on the bottom.
