### ISSUE TITLE
Migrations framework typos cause all sorts of errors 

### ISSUE THREAD

**Issue by usojoe** [susanBuck/dwa15-fall2015-notes#22]
Now that I'm just about wrapped up, I have some time to post some notes about where I ran into needless trouble that caused me hours of troubleshooting. Here's one that I recall frustrated me for about three straight days. 

In the migrations example: https://github.com/susanBuck/dwa15-fall2015-notes/blob/master/03_Laravel/17_Schemas_and_Migrations.md#up---build-the-table

The example incorrectly has:

$table->timestamps();

You will get all sorts of errors if you run that. Errors that look like this:

  [Illuminate\Database\QueryException]                                         
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'updated  
  _at' (SQL: create table `items` (`created_at` timestamp default 0 not null,  
   `updated_at` timestamp default 0 not null, `title` varchar(255) not null,   
  `item_number` int not null, `item_description` int not null, `initiated_at`  
   varchar(255) not null, `updated_at` varchar(255) not null) default charact  
  er set utf8 collate utf8_unicode_ci)       

Instead, it should be singular and read:

 $table->timestamp('created_at');

**Comment by susanBuck** [comment]
Hi Joe,

`timestamps()` is not a typo, nor is it incorrect.

Referring to the documentation (Migrations: Available Column Types)[http://laravel.com/docs/5.1/migrations], you will see that `timestamps()` (plural) is a valid method.

When using it it will create both a `created_at` and `updated_at` fields in your tables, which is what you want.

In fact, you successfully use it in [your categories table]().
And [your products table](https://github.com/bsmitty54/P4/blob/master/database/migrations/2015_11_03_011835_create_products_table.php)
And [your salespeople table](https://github.com/bsmitty54/P4/blob/master/database/migrations/2015_11_03_011853_create_salespeople_table.php)
And [your sales transactions tabl](https://github.com/bsmitty54/P4/blob/master/database/migrations/2015_11_03_011907_create_sales_transactions_table.php)

You would use `timestamp('created_at')` if you only wanted a `created_at`, not a `updated_at` field.
The only time we see this approach is in the `password_resets` table that comes with Laravel default. (Password resets are only ever created, never updated so it makes sense that we don't need a `updated_at` field there)

I'm a little confused where you identified this potential problem, as in all your migrations you're using `timestamps()` (plural). 

In the error you reported above, it looks like it's regarding a table called `items` which is not part of your migrations. Perhaps that table is now your `products` table? Even so, it's using `timestamps()` (plural).

If we take a closer look at the error itself it says this: 
```
Column already exists: 1060 Duplicate column name 'updated_at' `.  
```

Sure, if you already had a table with a `updated_at` field in it, switching from `timestamps()` to `timestamp('created_at`)` would circumvent that particular error, but it would be just that - a circumvention, and it would not indicate that `timestamps()` itself is an error or typo.

**Comment by usojoe** [comment]
Yeah sorry I realized this was my mistake. I just reverted my code back to
the timestamps() .. I still can't figure out what I was doing wrong but
it's working now. I tried to go and take it down but it was already gone.

**Comment by usojoe** [comment]
I think I might have had a duplicate (updated at) at some point in my
migrations which was causing me to have to work around it. Migrations was
tricky to learn .. I've always just populated with straight SQL...

On Fri, Dec 18, 2015 at 12:15 PM, Lee, Joseph <josephandrewlee@g.harvard.edu

**Comment by usojoe** [comment]
So,... yeah sorry about that. I kept getting hung up with errors trying to
get migrations to work so I kind of skipped learning the migration part and
just seeded my database with SQL and then went back to it and then when I
still couldn't figure out what I was doing wrong I figured out a
work-around by accident and posted that note. You are looking at a
different Joe's code.

I've since figured out that in my table structures I was repeating myself
with second "updated_at" call which was throwing the error.

Sorry about that. I did try and go remove it once I figured it out.

 - Joe

On Fri, Dec 18, 2015 at 12:17 PM, Lee, Joseph <josephandrewlee@g.harvard.edu
> wrote:

> I think I might have had a duplicate (updated at) at some point in my
> migrations which was causing me to have to work around it. Migrations was
> tricky to learn .. I've always just populated with straight SQL...
>
> On Fri, Dec 18, 2015 at 12:15 PM, Lee, Joseph <

**Comment by usojoe** [comment]
I was taking only that piece of your code and didn't realize I had my own "updated at" already in my migrations, so it was asking for the same thing twice. Once I changed it to singular "created at" well... that obviously fixed the problem because now I had one of each ... duh.    My bad. How do you delete these things?
