### ISSUE TITLE
alternative to Power Cycle to enable Apache2 config changes

### ISSUE THREAD

**Issue by extra808** [susanBuck/dwa15-fall2015-notes#3]
In 11_Live_domain_setup.md, it's suggested that you Power Cycle your DigitalOcean droplet through their web interface to make the Virtual Host changes to the Apache config take effect. Power cycling is a very "rough" way of treating a running system and the DigitalOcean discourages it. To restart for the Ubuntu command line you can instead use the `reboot` command which is equivalent to the more universal command `shutdown -r now`. Instead of using their Power Down web feature, use `poweroff` or `shutdown -h now`

But restarting the entire server is unnecessary to make a configuration change of just the web service take effect. Instead, use the command `service apache2 reload` or `service apache2 restart`. After making config changes it's also a good idea to first run `apachectl configtest` before reloading; it will check the syntax of the Apache config files so you can correct them before taking down the running service using a configuration that works.

**Comment by susanBuck** [comment]
All good points. In the past we went the Power Cycle route to try and minimize what was being done in CL vs. the more beginner-friendly GUI. It is a "rough" way of getting the job done, and while harmless in this context, not a good habit to get into.

Things have evolved enough that we're doing so much other work through the CL, though, I see no reason not to do the restart that way as well. I'll update the notes.

**Comment by markf3lton** [comment]
I agree that using "service apache2 restart" is faster.  However, there is definitely "beginner" value in showing students where the Power Cycle button is at Digital Ocean. 

There is also "beginner value" in getting folks into the habit of backing up server config files before editing or customizing them -- I like how you linked to the original.

**Comment by markf3lton** [comment]
A precautionary tale:  For some reason, I tried to make my "hello world" subdomain hyphenated, as in 
hello-world.MySite.com

This did not work at all.  Simply making it helloworld exactly as you have it in your notes was the solution.

**Comment by usojoe** [comment]
I think the hyphen messed me up. Now I have hyphens in some places and no hyphens in others. Even though I've deleted everything I can find with a hyphen I still see it in the pushing and fetching addresses from git.... help.

**Comment by susanBuck** [comment]
I just ran into an instance where the `service apache2 restart` approach beats the Power Cycle: If you have an error in your 000-default.conf file and try the `service apache2 restart` it will tell you about the error. If you Power Cycle, you'd have to dig into a log file to find the error.

**Comment by susanBuck** [comment]
https://github.com/susanBuck/dwa15-fall2015-notes/commit/2edb255c0c5484ac4607de097256c31ab825b72a

The error spotting benefits of `service apache2 restart` convinced me. Made the switch from Power Cycle to that. Thanks for the discussion everyone.

(Also emphasized how our example directory name was `hello-world` but the domain was `helloworld` as I can see Mark and Joe's points about that causing confusion.)
