### ISSUE TITLE
suggested addition to  01_Servers_and_Git / 07_Setup_Github.md 

### ISSUE THREAD

**Issue by MarkSheppard1** [susanBuck/dwa15-fall2015-notes#4]
If you create a passphrase when generating a new SSH key and then decide you want to remove it later, you can do so with the following command:
<pre> $ ssh-keygen -p -f ~\.ssh\id_rsa </pre>
(replace ~\.ssh\id_rsa with the location of your rsa key file)
You will be asked to provide your old passphrase, and then you can just hit enter (twice) at the new passphrase prompts to leave it blank. 
See more details on ssh-keygen with 
(Windows)<pre> $ ssh-keygen /? </pre> (Mac) <pre> man ssh-keygen </pre>

**Comment by susanBuck** [comment]
I like this tip. I'm not going to add it to the notes, just because It's an edge case, and I don't want to distract from the other main points. But, it'd make a good tip to share on Piazza!
