### ISSUE TITLE
gitprint 

### ISSUE THREAD

**Issue by LindaHorstmyer** [susanBuck/dwa15-fall2015-notes#5]
https://gitprint.com/susanBuck/dwa15-fall2015-notes/blob/1da4a5418d3dec9dffa083366431aaef6fa7b517/00_Command_Line/08_bashrc

The URL above is throwing the following error:

Something went wrong!
Oops, there was a problem connecting to Github to print this page. Check the URL and try again soon.

I have seen this several times.

**Comment by susanBuck** [comment]
Thanks for the head's up, Linda. Gitprint is an external resource, so I'm not sure what's going on here. That being said, I'll do some investigation and see if there's a good alternative.

**Comment by LindaHorstmyer** [comment]
Thanks Susan.  It seems to only happen on pages that look like this:

![capture](https://cloud.githubusercontent.com/assets/14101104/9815686/fb56b896-5865-11e5-96fe-33bce6a8c81d.JPG)

**Comment by susanBuck** [comment]
Ah, that explains it then. That page is from gist.github.com, which is Github's platform for sharing single page code files/examples.

For that case, I would not recommend using GitPrint for printing. Instead, click RAW and print that.

**Comment by LindaHorstmyer** [comment]
Great.  Thank you!
