### ISSUE TITLE
missing '$' in .bashrc template

### ISSUE THREAD

**Issue by extra808** [susanBuck/dwa15-fall2015-notes#7]
In the .bashrc template, `export VISUAL=text_editor` should be `export VISUAL=$text_editor` otherwise commands that invoke the `GIT_EDITOR` will result in errors like 
```
error: cannot run text_editor: No such file or directory
error: unable to start editor 'text_editor'
```

**Comment by susanBuck** [comment]
Another thanks! 
https://gist.github.com/susanBuck/ee3a0a53d72198c1a244/revisions
