### ISSUE TITLE
suggestion for addition to Increasing_server_security

### ISSUE THREAD

**Issue by depasq** [susanBuck/dwa15-fall2015-notes#9]
After creating the new user on the droplet and disabling root ssh access, you will need to generate a new ssh key (for the new user) and update the ssh settings in GitHub to allow the new user to pull updates from GitHub.

**Comment by susanBuck** [comment]
Added! 

https://github.com/susanBuck/dwa15-fall2015-notes/blob/master/01_Servers_and_Git/99_Extras/02_Increasing_server_security.md#new-ssh-key-for-github
